### ISSUE TITLE
Map UID

### ISSUE THREAD

**Issue by twocanoes** [twocanoes/xcreds#186] opened 2024-03-07 20:33 UTC
XCreds should be provide a way to map an OIDC or AD attribute for UID when creating the user account.

**Comment by mallej** [comment] 2024-03-12 14:04
Hi,
in response to the [question in slack:](https://macadmins.slack.com/archives/C03GBF2DE7P/p1709843612458419?thread_ts=1707230452.347719&cid=C03GBF2DE7P)
The login should fail if the UID is already used.
The claim name should be configurable.
Thank you

**Comment by mallej** [comment] 2024-04-02 07:34
look like a duplicate of https://github.com/twocanoes/xcreds/issues/74.
And yes, we are still interested in the function.

**Closed** 2024-06-13 03:26 UTC
