### ISSUE TITLE
Specify attribute returned from IdP to use as username

### ISSUE THREAD

**Issue by beckf** [twocanoes/xcreds#52] opened 2022-10-04 21:46 UTC
Allow configuration to specify a returned attribute from IdP to use as username. 

This would be great for backwards compatibility and deployment where their is a username already on the machine.

**Comment by twocanoes** [comment] 2022-10-07 02:58
OK, i went to implement this and not sure how best to do it. I suspect that you want to specify a value in prefs that specifies the value in the identity token to use. for example, my id token is:

{
  "aud": "5487c4cd-949a-402d-9eee-ae8fb696b415",
  "iss": "https://sts.windows.net/e64a2b5d-3eb1-436e-9e8a-521f0c5cd489/",
  "iat": 1665107810,
  "nbf": 1665107810,
  "exp": 1665111710,
  "amr": [
    "pwd"
  ],
  "family_name": "Rubble",
  "given_name": "Barney",
  "ipaddr": "73.73.108.22",
  "name": "barney",
  "nonce": "7BDD857F-41AE-4E50-A46F-BD1840D05CE0",
  "oid": "756c5c0d-7f28-422a-b9eb-a3f5c6d655c1",
  "rh": "0.AVkAXStK5rE-bkOeilIfDFzUic3Eh1SalC1Anu6uj7aWtBVZABI.",
  "sub": "a6VBIKM5g4638Q2undaONmOEVU-ISq1b8CihYDk8CDg",
  "tid": "e64a2b5d-3eb1-436e-9e8a-521f0c5cd489",
  "unique_name": "barney@twocanoes.com",
  "upn": "barney@twocanoes.com",
  "uti": "3S8LeuQI1UW1EAPQNQkAAA",
  "ver": "1.0"

So the preferences might have a value "mappedUsername" which would be "name". When i get the identity token back, i see that mappedUsername is name, and the token has a name key with "barney" as the username, so use that. Is that what you are suggesting?

**Comment by beckf** [comment] 2022-10-07 21:34
Yes it would be great to be able to just specify the claim field that gets used to create/verify the username.  Here is how I do it in JAMFConnect/NoMAD:

UnInstall-Module AzureAD

Install-Module AzureADPreview

Connect-AzureAD

New-AzureADPolicy -Definition @('{
                     "ClaimsMappingPolicy": {
                         "Version": 1,
                         "IncludeBasicClaimSet": "true",
                         "ClaimsSchema": [{
                                 "Source": "user",
                                 "ID": "employeeid",
                                 "SamlClaimType": "http://schemas.xmlsoap.org/ws/2005/05/identity/claims/employeeid",
                                 "JwtClaimType": "employeeid"
                             },
                             {
                                 "Source": "user",
                                 "ID": "onpremisessamaccountname",
                                 "SamlClaimType": "samaccountname",
                                 "JwtClaimType": "samAccountName"
                             },
                             {
                                 "Source": "user",
                                 "ID": "department",
                                 "SamlClaimType": "http://schemas.microsoft.com/identity/claims/department",
                                 "JwtClaimType": "department"
                             }
                         ]
                     }
                 }') -DisplayName "MacLoginPolicy" -Type "ClaimsMappingPolicy"
				 
New Azure Policy Object ID is returned to PowerShell. Use that and the ObjectID of App properties in Azure Enterprise Applications to assign the policy to the application.

Add-AzureADServicePrincipalPolicy -Id <azure-app-id> -RefObjectId <azure-policy-id>

Downloaded the Manifest for the app in Azure App Registrations.  Set "acceptMappedClaims": true and upload manifest back to App Registration.

The following token is now returned by JAMFConnect (sanitized).  Set "ROPG Short Name" in the profile to samAccountName.

{"preferred_username":"first.last@domain.org","sub":"...","tid":"...","iat":...,"employeeid":"...","amr":["..."],"samAccountName":"jsmith","rh":"0.....","mail":"first.last@domain.org","nbf":...,"oid":"...","uti":"...","iss":"https:\/\/sts.windows.net\/...e\/","family_name":"Beck","aud":"...","name":"Forrest Beck","nonce":"...","given_name":"Forrest","exp":...,"ver":"1.0","department":"...","upn":"first.last@domain.org","unique_name":"first.last@domain.org","ipaddr":"...","onprem_sid":"..."}

All accounts are now created/verified by samAccountName.

**Comment by beckf** [comment] 2022-10-25 10:57
Any further thoughts/progress in this?

**Comment by DoubleM-DCDSB** [comment] 2022-10-27 15:51
I would love the abiliity to use samaccountname.

**Comment by pekkasalonen** [comment] 2022-10-31 09:50
This is a duplicate of issue #45, right?

**Comment by twocanoes** [comment] 2022-11-09 03:21
check test PreBeta-XCreds_Build-3303_Version-2.2.pkg. Also, there is an update sample profile and manifest.

**Closed by twocanoes** 2022-11-09 03:21 UTC
